### ISSUE TITLE
Issue with recent andino_gz migration to harmonic

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino_rmf#22]
### Context

This PR: https://github.com/Ekumen-OS/andino_gz/pull/73 moves from fortress to harmonic andino_gz which is our dependency.

### Issue

This triggers a conflict in the packages due to our dependency to rmf packages (rmf_sim /rmf_demos) dependency which rely on fortress/humble packages. We are building [rmf_demos](https://github.com/open-rmf/rmf_demos) from source in our dockerfile

### Alternatives

- [ ] Check if we can narrow down the building of the packages, this is avoid rosdep install and build on packages like [rmf_demos_gz](https://github.com/open-rmf/rmf_demos/tree/humble/rmf_demos_gz)
- [ ] Wait for jazzy migration of andino_gz (not ideal) and migrate all this work to use Jazzy

**Comment by Voldivh** [comment]
Taking a look at the problem we certainly have a couple of options here. I would like to not have any dependency with [rmf_demos](https://github.com/open-rmf/rmf_demos). We currently have that because we were using one of their task examples nodes, we should create our own task nodes so we can lose this dependency. This would require some more bandwidth on this project since it is not a trivial task (not complex either).

**Comment by francocipollone** [comment]
That would be the ideal solution, however, we might have something easier:

Which packages are we using from rmf_demos? If we are only using https://github.com/open-rmf/rmf_demos/tree/main/rmf_demos_tasks

We could try to simply build and rosdep install the deps of the that one.

**Comment by Voldivh** [comment]
Yes, that is the only one we are actually using. I'll try that solution.

**Comment by francocipollone** [comment]
Dismissed as the migration to fortress is not needed
